### ISSUE TITLE
Publish tagged releases

### ISSUE THREAD

**Issue by larsrh** [gilith/opentheory#1]
There's a tarball on the website: http://www.gilith.com/software/opentheory/download.html

Unfortunately the tarball is not stable, i.e. it is updated in-place. This is a problem because it means builds from source are not reproducible.

It would be good if
1. release tarballs contained the actual revision (e.g. 1.3.20171122)
2. a tag would be pushed to the Git repository

**Comment by gilith** [comment]
Hi Lars,

Thanks for your build reproducibility suggestions. Right now the download website only provides the most recent version of the opentheory tool - for build reproducibility would it also be required to provide all past versions?

Cheers,

Joe

**Comment by larsrh** [comment]
Keeping the old tarballs around would be reasonable, I think. There's no particular need in linking to them, though.

Depending on whether or not you'd like to implement the second suggestion too, then that would make it even easier: GitHub provides tarballs for tagged releases automatically, and keeps them around indefinitely.

**Comment by larsrh** [comment]
That's no problem. Here's a [help article](https://help.github.com/articles/creating-releases/) describing how to attach arbitrary files to a release.

**Comment by gilith** [comment]
Thanks, Lars. I'm not going to change the gilith.com release, but from now on I will also make releases on GitHub.

I have just made the first such release that you can use for testing - please use the opentheory.tar.gz tarball that will be associated with each release and contains just the production files (rather than the "Source code" links that contain all the development files).

**Comment by larsrh** [comment]
Thanks, that's very helpful!
