### ISSUE TITLE
Modularising opentheory.sml

### ISSUE THREAD

**Issue by larsrh** [gilith/opentheory#2]
It is possible to load the entirety of OpenTheory's sources into Isabelle/ML.

A work in progress can be tracked in my fork: [topic/isabelle](https://github.com/gilith/opentheory/compare/master...larsrh:topic/isabelle).

There is one small problem, though: `opentheory.sml` contains a lot of code that provides a CLI entrypoint to OpenTheory. Loading it immediately quits the Isabelle process with the error message that the wrong CLI arguments are passed.

Would it be possible to provide a function `val opentheory: string list -> unit` instead? The entrypoint of OpenTheory could then just call that function with the CLI arguments.

**Comment by gilith** [comment]
Firstly, that's excellent news: great work.

Secondly, I'm having trouble understanding your use-case. The whole of the opentheory.sml file is the CLI interface to the opentheory tool, and the other files provide a kind of library interface (although I don't know of uses like this).

From your question it seems you want to load all the SML files including opentheory.sml, and then interact with it by calling a function that simulates invoking it on the command line.

1. Is this correct, or is there other functionality in opentheory.sml that you want to use but can't load because of this error?

2. If this is correct, what are the advantages of interacting with the tool this way over compiling it and calling it from ML like you would any other command line tool?

**Comment by larsrh** [comment]
> Is this correct …

Yes, it is.

> If this is correct, what are the advantages of interacting with the tool this way over compiling it and calling it from ML like you would any other command line tool?

Loading it into Isabelle is the easiest way to "pretend" that OpenTheory is an Isabelle tool. There are some other tools like that. Essentially, it is the easiest way to distribute third-party code for us; otherwise we'd have to tell users "download this, compile it on your platform, set some environment variables".

**Comment by larsrh** [comment]
As an addon: I'm not asking you to incorporate any specific Isabelle code into your repository. That would go into Isabelle directly. I've linked to it just for demonstration purposes.

**Comment by gilith** [comment]
I changed the code as you suggested: see the new `Tool` structure for the ML interface. Please let me know if it doesn't fit your needs.

Disclaimer: I have no idea what happens if you call the new `Tool.main` function multiple times. It might work, but this is untested behaviour.

**Comment by larsrh** [comment]
That's excellent, thanks! Single invocation will be quite sufficient, I think.

**Comment by larsrh** [comment]
This is now in https://github.com/isabelle-prover/opentheory-component.
