### ISSUE TITLE
in article files, how to handle unknown typeOp/const?

### ISSUE THREAD

**Issue by c-cube** [gilith/opentheory#7]
The theory file page describes theories as `\Gamma |- \Delta`, so purely on the theorem level. However there are also input constants in a theory, and defined constants, if I understand correctly.

When reading an article file (the VM instructions) there seems to be no explicit operation to create a constant/typeOp by pushing it into the theory being built's inputs? Or do `const`/`typeOp` implicitly create these constants?

On a semi-related note, I've noticed that there are a few "axiom" articles (choice, infinity, etc.) but they use the `axiom` command which just pushes a theorem into the current theory's assumptions. So is there no real axiom in the system, only assumptions that will never be discharged?

**Comment by gilith** [comment]
When processing an article there are 3 commands for accessing the theory context that the article is being read into: `typeOp`, `const`, and `axiom`. These are expected to be mapped to type operators, constants, and theorems that already exist in the theory context. The standard theory library defines and proves almost everything it needs, but it does rely on 3 primitive type operators, 2 primitive constants, and 3 primitive theorems to be present in the theory context. You can see them at the bottom of the `base` theory document: 

http://opentheory.gilith.com/opentheory/packages/base-1.221/base-1.221.html

You are correct that the 3 base axioms are technically theory assumptions, which means they only contain external symbols and have the potential to be satisfied by theorems in the theory context. Axioms that also contain symbols that are defined by the theory are true axioms, because they can never be satisfied by theorems in the theory context.

**Comment by c-cube** [comment]
So, when reading an `article` block, are all the constants of `require`d and `import`ed packages added to the scope before reading the article? That'd make sense given that my current error is that Data.Word.word isn't a known constant, but in a context where the theory has just been imported.

**Comment by gilith** [comment]
That is correct, where the symbols added to the context are all the symbols present in theorems proved by required packages and imported theory blocks. The exact processing of the theory blocks is spelled out in the following document:

http://www.gilith.com/opentheory/theory.html

The word theories are a little strange, because you're supposed to rename `word` to a type with a fixed width before proving the word theorems (it's like a theory with an argument symbol). For an example of this see the `word.int` interpretation file in the theory defining bytes: http://opentheory.gilith.com/opentheory/packages/byte-def-1.100/byte-def.thy

**Comment by c-cube** [comment]
I already had the part about interpretation files, but the context in which to interpret an article was what I missed. Thank you very much!
